[package]
name = "plog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.23"
lazy-regex = "2.3.0"
lazy_static = "1.4.0"
regex = "1.5.5"
